apiVersion: v1
kind: Service
metadata:
  name: {{ include "propconnect.fullname" . }}-backend
  namespace: {{ .Values.namespace | default .Release.Namespace }}
  labels:
    {{- include "propconnect.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: {{ include "propconnect.name" . }}
    app.kubernetes.io/component: backend
  ports:
    - name: http
      port: 5000
      targetPort: http