{{- if .Values.externalSecret.enabled }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Values.externalSecret.name | default (printf "%s-backend" (include "propconnect.fullname" .)) }}
  namespace: {{ .Values.namespace | default .Release.Namespace }}
  labels:
    {{- include "propconnect.labels" . | nindent 4 }}
spec:
  refreshPolicy: Periodic
  refreshInterval: {{ .Values.externalSecret.refreshInterval | default "1h" }}
  secretStoreRef:
    name: {{ .Values.externalSecret.storeName }}
    kind: ClusterSecretStore
  target:
    name: {{ .Values.externalSecret.targetName }}
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    - secretKey: MONGO_URI
      remoteRef:
        key: {{ .Values.externalSecret.remoteKey }}
        property: MONGO_URI
    - secretKey: JWT_SECRET
      remoteRef:
        key: {{ .Values.externalSecret.remoteKey }}
        property: JWT_SECRET
    - secretKey: JWT_EXPIRE
      remoteRef:
        key: {{ .Values.externalSecret.remoteKey }}
        property: JWT_EXPIRE
{{- end }}