{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "propconnect.fullname" . }}-allow-ingress
  namespace: {{ .Values.namespace | default .Release.Namespace }}
  labels:
    {{- include "propconnect.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: {{ include "propconnect.name" . }}
  policyTypes:
    - Ingress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: {{ .Values.networkPolicy.ingressNamespace | quote }}
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: {{ include "propconnect.name" . }}
{{- end }}