apiVersion: v1
kind: ConfigMap
metadata:
  name: propconnect-config
  namespace: propconnect
  labels:
    app.kubernetes.io/name: propconnect
    app.kubernetes.io/part-of: propconnect
data:
  NODE_ENV: production
  PORT: "5000"
  FRONTEND_URL: https://propconnect07.duckdns.org
