apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: propconnect
  namespace: propconnect
  labels:
    app.kubernetes.io/name: propconnect
    app.kubernetes.io/part-of: propconnect
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "1m"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - propconnect07.duckdns.org
      secretName: propconnect-tls
  rules:
    - host: propconnect07.duckdns.org
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: propconnect-backend
                port:
                  name: http
          - path: /
            pathType: Prefix
            backend:
              service:
                name: propconnect-frontend
                port:
                  name: http
