apiVersion: v1
kind: ServiceAccount
metadata:
  name: propconnect-app
  namespace: propconnect
  labels:
    app.kubernetes.io/name: propconnect
    app.kubernetes.io/part-of: propconnect
automountServiceAccountToken: false
