name: docker pipeline
on:
  workflow_dispatch:
  push:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: docker build
        run: |
          docker build -f docker/Dockerfile -t frontend:latest .

      - name: check docker images
        run: |
          docker images
        
      - name: Archive Docker Image
        run: docker save frontend:latest -o frontend-image.tar

      - name: Upload Docker Image Artifact
        uses: actions/upload-artifact@v7
        with:
          name: frontend-image
          path: frontend-image.tar
          retention-days: 5