name: ci-cd

on:
  workflow_dispatch:

jobs:
  ci-propconnect:
    runs-on: ubuntu-latest
    steps:
      - name: clone
        uses: actions/checkout@v6

      - name: node -v
        run: node -v
        shell: bash