name: ci-cd

on:
  workflow_dispatch:

jobs:
  ci-propconnect:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: clone
        uses: actions/checkout@v6

      - name: node -v
        run: node -v

      - name: running npm force
        run: |
          ls -la
          cd frontend
          npm i --force
          cd ..
          cd backend
          npm i --force
          ls -la